import type { User } from '@/types'

export const dummyUsers: User[] = [
    {
        id: 'admin',
        email: 'admin@tennis-club.com',
        name: '장관우',
        nickname: '관우',
        role: 'admin',
        phone: '010-9000-0000',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 5.0,
        tennisStartDate: '2010-03-01',
        createdAt: '2024-01-01',
    },
    {
        id: 'user-1',
        email: 'member1@tennis-club.com',
        name: '김태준',
        nickname: '태준',
        role: 'member',
        phone: '010-1001-2001',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 4.0,
        tennisStartDate: '2018-03-01',
        createdAt: '2024-01-10',
    },
    {
        id: 'user-2',
        email: 'member2@tennis-club.com',
        name: '이수연',
        nickname: '수연',
        role: 'member',
        phone: '010-1002-2002',
        gender: 'female',
        dominantHand: 'right',
        ntrp: 3.0,
        tennisStartDate: '2020-06-01',
        createdAt: '2024-01-15',
    },
    {
        id: 'user-3',
        email: 'member3@tennis-club.com',
        name: '박준혁',
        nickname: '준혁',
        role: 'member',
        phone: '010-1003-2003',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 4.5,
        tennisStartDate: '2016-02-01',
        createdAt: '2024-01-20',
    },
    {
        id: 'user-4',
        email: 'member4@tennis-club.com',
        name: '최유나',
        nickname: '유나',
        role: 'member',
        phone: '010-1004-2004',
        gender: 'female',
        dominantHand: 'left',
        ntrp: 3.0,
        tennisStartDate: '2021-04-01',
        createdAt: '2024-01-25',
    },
    {
        id: 'user-5',
        email: 'member5@tennis-club.com',
        name: '정민준',
        nickname: '민준',
        role: 'member',
        phone: '010-1005-2005',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 3.5,
        tennisStartDate: '2019-09-01',
        createdAt: '2024-02-01',
    },
    {
        id: 'user-6',
        email: 'member6@tennis-club.com',
        name: '강지은',
        nickname: '지은',
        role: 'member',
        phone: '010-1006-2006',
        gender: 'female',
        dominantHand: 'right',
        ntrp: 2.5,
        tennisStartDate: '2022-07-01',
        createdAt: '2024-02-05',
    },
    {
        id: 'user-7',
        email: 'member7@tennis-club.com',
        name: '한승우',
        nickname: '승우',
        role: 'member',
        phone: '010-1007-2007',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 3.5,
        tennisStartDate: '2019-11-01',
        createdAt: '2024-02-10',
    },
    {
        id: 'user-8',
        email: 'member8@tennis-club.com',
        name: '윤서연',
        nickname: '서연',
        role: 'member',
        phone: '010-1008-2008',
        gender: 'female',
        dominantHand: 'right',
        ntrp: 2.5,
        tennisStartDate: '2021-05-01',
        createdAt: '2024-02-15',
    },
    {
        id: 'user-9',
        email: 'member9@tennis-club.com',
        name: '송지훈',
        nickname: '지훈',
        role: 'member',
        phone: '010-1009-2009',
        gender: 'male',
        dominantHand: 'left',
        ntrp: 4.0,
        tennisStartDate: '2017-12-01',
        createdAt: '2024-02-20',
    },
    {
        id: 'user-10',
        email: 'member10@tennis-club.com',
        name: '임하은',
        nickname: '하은',
        role: 'member',
        phone: '010-1010-2010',
        gender: 'female',
        dominantHand: 'right',
        ntrp: 3.5,
        tennisStartDate: '2019-08-01',
        createdAt: '2024-03-01',
    },
    {
        id: 'user-11',
        email: 'member11@tennis-club.com',
        name: '오현석',
        nickname: '현석',
        role: 'member',
        phone: '010-1011-2011',
        gender: 'male',
        dominantHand: 'right',
        ntrp: 3.0,
        tennisStartDate: '2020-03-01',
        createdAt: '2024-03-05',
    },
    {
        id: 'user-12',
        email: 'member12@tennis-club.com',
        name: '배지현',
        nickname: '지현',
        role: 'member',
        phone: '010-1012-2012',
        gender: 'female',
        dominantHand: 'right',
        ntrp: 2.5,
        tennisStartDate: '2023-01-01',
        createdAt: '2024-03-10',
    },
]

export function getUserById(id: string): User | undefined {
    return dummyUsers.find((u) => u.id === id)
}
